/**************************************************
LEADTOOLS (C) 1991-2015 LEAD Technologies, Inc. ALL RIGHTS RESERVED.
This software is protected by United States and International copyright laws.
Any copying, duplication, deployment, redistribution, modification or other
disposition hereof is STRICTLY PROHIBITED without an express written license
granted by LEAD Technologies, Inc.. This notice may not be removed or otherwise
altered under any circumstances.
Portions of this product are licensed under US patent 5,327,254 and foreign
counterparts.
For more information, contact LEAD Technologies, Inc. at 704-332-5532 or visit
http://www.leadtools.com
**************************************************/
// Leadtools.js
// Version:19.0.0.1
(function(a){function b(a){this.__typeName=a}a.ss={version:"0.7.6.0",isUndefined:function(a){return void 0===a},isNull:function(a){return null===a},isNullOrUndefined:function(a){return null===a||void 0===a},isValue:function(a){return null!==a&&void 0!==a}};Object.__typeName="Object";Object.__baseType=null;Object.clearKeys=function(a){for(var b in a)delete a[b]};Object.keyExists=function(a,b){return void 0!==a[b]};Object.keys?Object.getKeyCount=function(a){return Object.keys(a).length}:(Object.keys=
function(a){var b=[],c;for(c in a)b.push(c);return b},Object.getKeyCount=function(a){var b=0,c;for(c in a)b++;return b});Boolean.__typeName="Boolean";Boolean.parse=function(a){return a.toLowerCase()=="true"};Number.__typeName="Number";Number.parse=function(a){return!a||!a.length?0:a.indexOf(".")>=0||a.indexOf("e")>=0||a.endsWith("f")||a.endsWith("F")?parseFloat(a):parseInt(a,10)};Number.prototype.format=function(a){return ss.isNullOrUndefined(a)||a.length==0||a=="i"?this.toString():this._netFormat(a,
false)};Number.prototype.localeFormat=function(a){return ss.isNullOrUndefined(a)||a.length==0||a=="i"?this.toLocaleString():this._netFormat(a,true)};Number._commaFormat=function(a,b,c,f){var d=null,c=a.indexOf(c);if(c>0){d=a.substr(c);a=a.substr(0,c)}(c=a.startsWith("-"))&&(a=a.substr(1));var h=0,l=b[h];if(a.length<l)return d?a+d:a;for(var g=a.length,n="",p=false;!p;){var o=l,m=g-o;if(m<0){l=l+m;o=o+m;m=0;p=true}if(!o)break;m=a.substr(m,o);n=n.length?m+f+n:m;g=g-o;if(h<b.length-1){h++;l=b[h]}}c&&
(n="-"+n);return d?n+d:n};Number.prototype._netFormat=function(a,b){var c=b?ss.CultureInfo.CurrentCulture.numberFormat:ss.CultureInfo.InvariantCulture.numberFormat,f="",d=-1;a.length>1&&(d=parseInt(a.substr(1)));var h=a.charAt(0);switch(h){case "d":case "D":f=parseInt(Math.abs(this)).toString();d!=-1&&(f=f.padLeft(d,"0"));this<0&&(f="-"+f);break;case "x":case "X":f=parseInt(Math.abs(this)).toString(16);h=="X"&&(f=f.toUpperCase());d!=-1&&(f=f.padLeft(d,"0"));break;case "e":case "E":f=d==-1?this.toExponential():
this.toExponential(d);h=="E"&&(f=f.toUpperCase());break;case "f":case "F":case "n":case "N":if(d==-1)d=c.numberDecimalDigits;f=this.toFixed(d).toString();if(d&&c.numberDecimalSeparator!="."){d=f.indexOf(".");f=f.substr(0,d)+c.numberDecimalSeparator+f.substr(d+1)}if(h=="n"||h=="N")f=Number._commaFormat(f,c.numberGroupSizes,c.numberDecimalSeparator,c.numberGroupSeparator);break;case "c":case "C":if(d==-1)d=c.currencyDecimalDigits;f=Math.abs(this).toFixed(d).toString();if(d&&c.currencyDecimalSeparator!=
"."){d=f.indexOf(".");f=f.substr(0,d)+c.currencyDecimalSeparator+f.substr(d+1)}f=Number._commaFormat(f,c.currencyGroupSizes,c.currencyDecimalSeparator,c.currencyGroupSeparator);f=this<0?String.format(c.currencyNegativePattern,f):String.format(c.currencyPositivePattern,f);break;case "p":case "P":if(d==-1)d=c.percentDecimalDigits;f=(Math.abs(this)*100).toFixed(d).toString();if(d&&c.percentDecimalSeparator!="."){d=f.indexOf(".");f=f.substr(0,d)+c.percentDecimalSeparator+f.substr(d+1)}f=Number._commaFormat(f,
c.percentGroupSizes,c.percentDecimalSeparator,c.percentGroupSeparator);f=this<0?String.format(c.percentNegativePattern,f):String.format(c.percentPositivePattern,f)}return f};String.__typeName="String";String.Empty="";String.compare=function(a,b,c){if(c){a&&(a=a.toUpperCase());b&&(b=b.toUpperCase())}a=a||"";b=b||"";return a==b?0:a<b?-1:1};String.prototype.compareTo=function(a,b){return String.compare(this,a,b)};String.concat=function(){return arguments.length===2?arguments[0]+arguments[1]:Array.prototype.join.call(arguments,
"")};String.prototype.endsWith=function(a){return!a.length?true:a.length>this.length?false:this.substr(this.length-a.length)==a};String.equals=function(a,b,c){return String.compare(a,b,c)==0};String._format=function(a,b,c){if(!String._formatRE)String._formatRE=/(\{[^\}^\{]+\})/g;return a.replace(String._formatRE,function(a,e){var d=parseInt(e.substr(1)),d=b[d+1];if(ss.isNullOrUndefined(d))return"";if(d.format){var l=null,g=e.indexOf(":");g>0&&(l=e.substring(g+1,e.length-1));return c?d.localeFormat(l):
d.format(l)}return c?d.toLocaleString():d.toString()})};String.format=function(a){return String._format(a,arguments,false)};String.fromChar=function(a,b){for(var c=a,f=1;f<b;f++)c=c+a;return c};String.prototype.htmlDecode=function(){var a=document.createElement("div");a.innerHTML=this;return a.textContent||a.innerText};String.prototype.htmlEncode=function(){var a=document.createElement("div");a.appendChild(document.createTextNode(this));return a.innerHTML.replace(/\"/g,"&quot;")};String.prototype.indexOfAny=
function(a,b,c){var f=this.length;if(!f)return-1;b=b||0;c=b+(c||f)-1;for(c>=f&&(c=f-1);b<=c;b++)if(a.indexOf(this.charAt(b))>=0)return b;return-1};String.prototype.insert=function(a,b){if(!b)return this.valueOf();if(!a)return b+this;var c=this.substr(0,a),f=this.substr(a);return c+b+f};String.isNullOrEmpty=function(a){return!a||!a.length};String.isNullOrWhiteSpace=function(a){return String.isNullOrEmpty(a)||a.trim()===""};String.prototype.lastIndexOfAny=function(a,b,c){var f=this.length;if(!f)return-1;
b=b||f-1;c=b-(c||f)+1;for(c<0&&(c=0);b>=c;b--)if(a.indexOf(this.charAt(b))>=0)return b;return-1};String.localeFormat=function(a){return String._format(a,arguments,true)};String.prototype.padLeft=function(a,b){return this.length<a?String.fromChar(b||" ",a-this.length)+this:this.valueOf()};String.prototype.padRight=function(a,b){return this.length<a?this+String.fromChar(b||" ",a-this.length):this.valueOf()};String.prototype.remove=function(a,b){return!b||a+b>this.length?this.substr(0,a):this.substr(0,
a)+this.substr(a+b)};String.prototype.replaceAll=function(a,b){return this.split(a).join(b||"")};String.prototype.startsWith=function(a){return!a.length?true:a.length>this.length?false:this.substr(0,a.length)==a};String.prototype.trim||(String.prototype.trim=function(){return this.trimEnd().trimStart()});String.prototype.trimEnd=function(){return this.replace(/\s*$/,"")};String.prototype.trimStart=function(){return this.replace(/^\s*/,"")};Array.__typeName="Array";Array.__interfaces=[ss.IEnumerable];
Array.prototype.add=function(a){this[this.length]=a};Array.prototype.addRange=function(a){this.push.apply(this,a)};Array.prototype.clear=function(){this.length=0};Array.prototype.clone=function(){return this.length===1?[this[0]]:Array.apply(null,this)};Array.prototype.contains=function(a){return this.indexOf(a)>=0};Array.prototype.dequeue=function(){return this.shift()};Array.prototype.enqueue=function(a){this._queue=true;this.push(a)};Array.prototype.peek=function(){return this.length?this[this._queue?
0:this.length-1]:null};Array.prototype.every||(Array.prototype.every=function(a,b){for(var c=this.length,f=0;f<c;f++)if(f in this&&!a.call(b,this[f],f,this))return false;return true});Array.prototype.extract=function(a,b){return!b?this.slice(a):this.slice(a,a+b)};Array.prototype.filter||(Array.prototype.filter=function(a,b){for(var c=this.length,f=[],d=0;d<c;d++)if(d in this){var h=this[d];a.call(b,h,d,this)&&f.push(h)}return f});Array.prototype.forEach||(Array.prototype.forEach=function(a,b){for(var c=
this.length,f=0;f<c;f++)f in this&&a.call(b,this[f],f,this)});Array.prototype.getEnumerator=function(){return new ss.ArrayEnumerator(this)};Array.prototype.groupBy=function(a,b){for(var c=this.length,f=[],d={},h=0;h<c;h++)if(h in this){var l=a.call(b,this[h],h);if(!String.isNullOrEmpty(l)){var g=d[l];if(!g){g=[];g.key=l;d[l]=g;f.add(g)}g.add(this[h])}}return f};Array.prototype.index=function(a,b){for(var c=this.length,f={},d=0;d<c;d++)if(d in this){var h=a.call(b,this[d],d);String.isNullOrEmpty(h)||
(f[h]=this[d])}return f};Array.prototype.indexOf||(Array.prototype.indexOf=function(a,b){var c=this.length;if(c)for(var d=b||0;d<c;d++)if(this[d]===a)return d;return-1});Array.prototype.insert=function(a,b){this.splice(a,0,b)};Array.prototype.insertRange=function(a,b){if(a===0)this.unshift.apply(this,b);else for(var c=0;c<b.length;c++)this.splice(a+c,0,b[c])};Array.prototype.lastIndexOf||(Array.prototype.lastIndexOf=function(a,b){for(var c=b=b||this.length-1;c>=0;c--)if(this[c]===a)return c;return-1});
Array.prototype.map||(Array.prototype.map=function(a,b){for(var c=this.length,d=Array(c),j=0;j<c;j++)j in this&&(d[j]=a.call(b,this[j],j,this));return d});Array.parse=function(a){return eval("("+a+")")};Array.prototype.reduce||(Array.prototype.reduce=function(a,b){var c=b,d=this.length;if(d){var j=0;if(arguments.length==1){c=this[0];j++}for(;j<d;j++)c=a(c,this[j],j,this)}return c},Array.prototype.reduceRight=function(a,b){var c=b,d=this.length;if(d){d=d-1;if(arguments.length==1){c=this[d];d--}for(;d>=
0;d--)c=a(c,this[d],d,this)}return c});Array.prototype.remove=function(a){a=this.indexOf(a);if(a>=0){this.splice(a,1);return true}return false};Array.prototype.removeAt=function(a){this.splice(a,1)};Array.prototype.removeRange=function(a,b){return this.splice(a,b)};Array.prototype.some||(Array.prototype.some=function(a,b){for(var c=this.length,d=0;d<c;d++)if(d in this&&a.call(b,this[d],d,this))return true;return false});Array.toArray=function(a){return Array.prototype.slice.call(a)};RegExp.__typeName=
"RegExp";RegExp.parse=function(a){if(a.startsWith("/")){var b=a.lastIndexOf("/");if(b>1){var c=a.substring(1,b),a=a.substr(b+1);return RegExp(c,a)}}return null};Date.__typeName="Date";Date.empty=null;Date.get_now=function(){return new Date};Date.get_today=function(){var a=new Date;return new Date(a.getFullYear(),a.getMonth(),a.getDate())};Date.isEmpty=function(a){return a===null||a.valueOf()===0};Date.prototype.format=function(a){return ss.isNullOrUndefined(a)||a.length==0||a=="i"?this.toString():
a=="id"?this.toDateString():a=="it"?this.toTimeString():this._netFormat(a,false)};Date.prototype.localeFormat=function(a){return ss.isNullOrUndefined(a)||a.length==0||a=="i"?this.toLocaleString():a=="id"?this.toLocaleDateString():a=="it"?this.toLocaleTimeString():this._netFormat(a,true)};Date.prototype._netFormat=function(a,b){var c=this,d=b?ss.CultureInfo.CurrentCulture.dateFormat:ss.CultureInfo.InvariantCulture.dateFormat;if(a.length==1)switch(a){case "f":a=d.longDatePattern+" "+d.shortTimePattern;
break;case "F":a=d.dateTimePattern;break;case "d":a=d.shortDatePattern;break;case "D":a=d.longDatePattern;break;case "t":a=d.shortTimePattern;break;case "T":a=d.longTimePattern;break;case "g":a=d.shortDatePattern+" "+d.shortTimePattern;break;case "G":a=d.shortDatePattern+" "+d.longTimePattern;break;case "R":case "r":d=ss.CultureInfo.InvariantCulture.dateFormat;a=d.gmtDateTimePattern;break;case "u":a=d.universalDateTimePattern;break;case "U":a=d.dateTimePattern;c=new Date(c.getUTCFullYear(),c.getUTCMonth(),
c.getUTCDate(),c.getUTCHours(),c.getUTCMinutes(),c.getUTCSeconds(),c.getUTCMilliseconds());break;case "s":a=d.sortableDateTimePattern}a.charAt(0)=="%"&&(a=a.substr(1));if(!Date._formatRE)Date._formatRE=/'.*?[^\\]'|dddd|ddd|dd|d|MMMM|MMM|MM|M|yyyy|yy|y|hh|h|HH|H|mm|m|ss|s|tt|t|fff|ff|f|zzz|zz|z/g;var j=Date._formatRE,h=new ss.StringBuilder;for(j.lastIndex=0;;){var l=j.lastIndex,g=j.exec(a);h.append(a.slice(l,g?g.index:a.length));if(!g)break;g=l=g[0];switch(l){case "dddd":g=d.dayNames[c.getDay()];break;
case "ddd":g=d.shortDayNames[c.getDay()];break;case "dd":g=c.getDate().toString().padLeft(2,"0");break;case "d":g=c.getDate();break;case "MMMM":g=d.monthNames[c.getMonth()];break;case "MMM":g=d.shortMonthNames[c.getMonth()];break;case "MM":g=(c.getMonth()+1).toString().padLeft(2,"0");break;case "M":g=c.getMonth()+1;break;case "yyyy":g=c.getFullYear();break;case "yy":g=(c.getFullYear()%100).toString().padLeft(2,"0");break;case "y":g=c.getFullYear()%100;break;case "h":case "hh":(g=c.getHours()%12)?
l=="hh"&&(g=g.toString().padLeft(2,"0")):g="12";break;case "HH":g=c.getHours().toString().padLeft(2,"0");break;case "H":g=c.getHours();break;case "mm":g=c.getMinutes().toString().padLeft(2,"0");break;case "m":g=c.getMinutes();break;case "ss":g=c.getSeconds().toString().padLeft(2,"0");break;case "s":g=c.getSeconds();break;case "t":case "tt":g=c.getHours()<12?d.amDesignator:d.pmDesignator;l=="t"&&(g=g.charAt(0));break;case "fff":g=c.getMilliseconds().toString().padLeft(3,"0");break;case "ff":g=c.getMilliseconds().toString().padLeft(3).substr(0,
2);break;case "f":g=c.getMilliseconds().toString().padLeft(3).charAt(0);break;case "z":g=c.getTimezoneOffset()/60;g=(g>=0?"-":"+")+Math.floor(Math.abs(g));break;case "zz":case "zzz":g=c.getTimezoneOffset()/60;g=(g>=0?"-":"+")+Math.floor(Math.abs(g)).toString().padLeft(2,"0");l=="zzz"&&(g=g+(d.timeSeparator+Math.abs(c.getTimezoneOffset()%60).toString().padLeft(2,"0")));break;default:g.charAt(0)=="'"&&(g=g.substr(1,g.length-2).replace(/\\'/g,"'"))}h.append(g)}return h.toString()};Date.parseDate=function(a){return new Date(Date.parse(a))};
Error.__typeName="Error";Error.prototype.popStackFrame=function(){if(!ss.isNullOrUndefined(this.stack)&&!ss.isNullOrUndefined(this.fileName)&&!ss.isNullOrUndefined(this.lineNumber)){for(var a=this.stack.split("\n"),b=a[0],c=this.fileName+":"+this.lineNumber;!ss.isNullOrUndefined(b)&&b.indexOf(c)===-1;){a.shift();b=a[0]}b=a[1];if(!isNullOrUndefined(b)){b=b.match(/@(.*):(\d+)$/);if(!ss.isNullOrUndefined(b)){a.shift();this.stack=a.join("\n");this.fileName=b[1];this.lineNumber=parseInt(b[2])}}}};Error.createError=
function(a,b,c){a=Error(a);if(b)for(var d in b)a[d]=b[d];if(c)a.innerException=c;a.popStackFrame();return a};a.console||(a.console={log:function(){},assert:function(){}});console.fail=function(b){console.assert(false,b);a.navigator&&a.navigator.userAgent.indexOf("MSIE")>0&&eval("debugger;")};a.Type=Function;Type.__typeName="Type";var c={},d=[];b.prototype={__namespace:!0,getName:function(){return this.__typeName}};Type.registerNamespace=function(e){if(!c[e]){for(var i=a,k=e.split("."),f=0;f<k.length;f++){var j=
k[f],h=i[j];if(!h){i[j]=h=new b(k.slice(0,f+1).join("."));f==0&&d.add(h)}i=h}c[e]=i}};Type.prototype.registerClass=function(a,b,c){this.prototype.constructor=this;this.__typeName=a;this.__class=true;this.__baseType=b||Object;if(b)this.__basePrototypePending=true;if(c){this.__interfaces=[];for(var d=2;d<arguments.length;d++){c=arguments[d];this.__interfaces.add(c)}}};Type.prototype.registerInterface=function(a){this.__typeName=a;this.__interface=true};Type.prototype.registerEnum=function(a,b){for(var c in this.prototype)this[c]=
this.prototype[c];this.__typeName=a;this.__enum=true;if(b)this.__flags=true};Type.prototype.setupBase=function(){if(this.__basePrototypePending){var a=this.__baseType;a.__basePrototypePending&&a.setupBase();for(var b in a.prototype){var c=Object.getOwnPropertyDescriptor(a.prototype,b);c&&(c.get||c.set)?!Object.getOwnPropertyDescriptor(this.prototype,b)&&Object.defineProperty(this.prototype,b,c):this.prototype[b]||(this.prototype[b]=a.prototype[b])}delete this.__basePrototypePending}};Type.prototype.resolveInheritance||
(Type.prototype.resolveInheritance=Type.prototype.setupBase);Type.prototype.initializeBase=function(a,b){this.__basePrototypePending&&this.setupBase();b?this.__baseType.apply(a,b):this.__baseType.apply(a)};Type.prototype.callBaseMethod=function(a,b,c){b=this.__baseType.prototype[b];return!c?b.apply(a):b.apply(a,c)};Type.prototype.get_baseType=function(){return this.__baseType||null};Type.prototype.get_fullName=function(){return this.__typeName};Type.prototype.get_name=function(){var a=this.__typeName,
b=a.lastIndexOf(".");return b>0?a.substr(b+1):a};Type.prototype.isInstanceOfType=function(a){return ss.isNullOrUndefined(a)?false:this==Object||a instanceof this?true:this.isAssignableFrom(Type.getInstanceType(a))};Type.prototype.isAssignableFrom=function(a){if(this==Object||this==a)return true;if(this.__class)for(a=a.__baseType;a;){if(this==a)return true;a=a.__baseType}else if(this.__interface){var b=a.__interfaces;if(b&&b.contains(this))return true;for(a=a.__baseType;a;){if((b=a.__interfaces)&&
b.contains(this))return true;a=a.__baseType}}return false};Type.isClass=function(a){return a.__class==true};Type.isInterface=function(a){return a.__interface==true};Type.canCast=function(a,b){return b.isInstanceOfType(a)};Type.safeCast=function(a,b){return b.isInstanceOfType(a)?a:null};Type.getInstanceType=function(a){var b=null;try{b=a.constructor}catch(c){}if(!b||!b.__typeName)b=Object;return b};Type.getType=function(a){if(!a)return null;if(!Type.__typeCache)Type.__typeCache={};var b=Type.__typeCache[a];
if(!b){b=eval(a);Type.__typeCache[a]=b}return b};ss.Delegate=function(){};ss.Delegate.registerClass("Delegate");ss.Delegate.empty=function(){};ss.Delegate._contains=function(a,b,c){for(var d=0;d<a.length;d=d+2)if(a[d]===b&&a[d+1]===c)return true;return false};ss.Delegate._create=function(a){var b=function(){if(a.length==2)return a[1].apply(a[0],arguments);for(var b=a.clone(),c=0;c<b.length;c=c+2)ss.Delegate._contains(a,b[c],b[c+1])&&b[c+1].apply(b[c],arguments);return null};b._targets=a;return b};
ss.Delegate.create=function(a,b){return!a?b:ss.Delegate._create([a,b])};ss.Delegate.combine=function(a,b){return!a?!b._targets?ss.Delegate.create(null,b):b:!b?!a._targets?ss.Delegate.create(null,a):a:ss.Delegate._create((a._targets?a._targets:[null,a]).concat(b._targets?b._targets:[null,b]))};ss.Delegate.remove=function(a,b){if(!a||a===b)return null;if(!b)return a;var c=a._targets,d=null,j;if(b._targets){d=b._targets[0];j=b._targets[1]}else j=b;for(var h=0;h<c.length;h=h+2)if(c[h]===d&&c[h+1]===j){if(c.length==
2)return null;c.splice(h,2);return ss.Delegate._create(c)}return a};ss.Delegate.createExport=function(b,c,d){d=d||"__"+(new Date).valueOf();a[d]=c?b:function(){try{delete a[d]}catch(c){a[d]=void 0}b.apply(null,arguments)};return d};ss.Delegate.deleteExport=function(b){delete a[b]};ss.Delegate.clearExport=function(b){a[b]=ss.Delegate.empty};ss.CultureInfo=function(a,b,c){this.name=a;this.numberFormat=b;this.dateFormat=c};ss.CultureInfo.registerClass("CultureInfo");ss.CultureInfo.InvariantCulture=new ss.CultureInfo("en-US",
{naNSymbol:"NaN",negativeSign:"-",positiveSign:"+",negativeInfinityText:"-Infinity",positiveInfinityText:"Infinity",percentSymbol:"%",percentGroupSizes:[3],percentDecimalDigits:2,percentDecimalSeparator:".",percentGroupSeparator:",",percentPositivePattern:"{0} %",percentNegativePattern:"-{0} %",currencySymbol:"$",currencyGroupSizes:[3],currencyDecimalDigits:2,currencyDecimalSeparator:".",currencyGroupSeparator:",",currencyNegativePattern:"(${0})",currencyPositivePattern:"${0}",numberGroupSizes:[3],
numberDecimalDigits:2,numberDecimalSeparator:".",numberGroupSeparator:","},{amDesignator:"AM",pmDesignator:"PM",dateSeparator:"/",timeSeparator:":",gmtDateTimePattern:"ddd, dd MMM yyyy HH:mm:ss 'GMT'",universalDateTimePattern:"yyyy-MM-dd HH:mm:ssZ",sortableDateTimePattern:"yyyy-MM-ddTHH:mm:ss",dateTimePattern:"dddd, MMMM dd, yyyy h:mm:ss tt",longDatePattern:"dddd, MMMM dd, yyyy",shortDatePattern:"M/d/yyyy",longTimePattern:"h:mm:ss tt",shortTimePattern:"h:mm tt",firstDayOfWeek:0,dayNames:"Sunday,Monday,Tuesday,Wednesday,Thursday,Friday,Saturday".split(","),
shortDayNames:"Sun,Mon,Tue,Wed,Thu,Fri,Sat".split(","),minimizedDayNames:"Su,Mo,Tu,We,Th,Fr,Sa".split(","),monthNames:"January,February,March,April,May,June,July,August,September,October,November,December,".split(","),shortMonthNames:"Jan,Feb,Mar,Apr,May,Jun,Jul,Aug,Sep,Oct,Nov,Dec,".split(",")});ss.CultureInfo.CurrentCulture=ss.CultureInfo.InvariantCulture;ss.IEnumerator=function(){};ss.IEnumerator.getEnumerator=function(a){return a?a.getEnumerator?a.getEnumerator():new ss.ArrayEnumerator(a):null};
ss.IEnumerator.registerInterface("IEnumerator");ss.IEnumerable=function(){};ss.IEnumerable.registerInterface("IEnumerable");ss.ArrayEnumerator=function(a){this._array=a;this._index=-1;this.current=null};ss.ArrayEnumerator.prototype={moveNext:function(){this._index++;this.current=this._array[this._index];return this._index<this._array.length},reset:function(){this._index=-1;this.current=null}};ss.ArrayEnumerator.registerClass("ArrayEnumerator",null,ss.IEnumerator);ss.IDisposable=function(){};ss.IDisposable.registerInterface("IDisposable");
ss.StringBuilder=function(a){this._parts=ss.isNullOrUndefined(a)||a===""?[]:[a];this.isEmpty=this._parts.length==0};ss.StringBuilder.prototype={append:function(a){if(!ss.isNullOrUndefined(a)&&a!==""){this._parts.add(a);this.isEmpty=false}return this},appendLine:function(a){this.append(a);this.append("\r\n");this.isEmpty=false;return this},clear:function(){this._parts=[];this.isEmpty=true},toString:function(a){return this._parts.join(a||"")}};ss.StringBuilder.registerClass("StringBuilder");ss.EventArgs=
function(){};ss.EventArgs.registerClass("EventArgs");ss.EventArgs.Empty=new ss.EventArgs;ss.EventHandler=function(){};ss.EventHandler.registerClass("EventHandler");ss.EventHandler.create=function(a,b,c){var d=new ss.EventHandler;d._target=a;d._addFunction=b;d._removeFunction=c;return d};ss.EventHandler.prototype={_target:null,_addFunction:null,_removeFunction:null,add:function(a){this._target?this._addFunction.call(this._target,a):this._addFunction(a);return a},remove:function(a){this._target?this._removeFunction.call(this._target,
a):this._removeFunction(a)}};ss.CancelEventArgs=function(){ss.CancelEventArgs.initializeBase(this);this.cancel=false};ss.CancelEventArgs.registerClass("CancelEventArgs",ss.EventArgs);ss.Tuple=function(a,b,c){this.first=a;this.second=b;if(arguments.length==3)this.third=c};ss.Tuple.registerClass("Tuple");ss.Observable=function(a){this._v=a;this._observers=null};ss.Observable.prototype={getValue:function(){this._observers=ss.Observable._captureObservers(this._observers);return this._v},setValue:function(a){if(this._v!==
a){this._v=a;if(a=this._observers){this._observers=null;ss.Observable._invalidateObservers(a)}}}};ss.Observable._observerStack=[];ss.Observable._observerRegistration={dispose:function(){ss.Observable._observerStack.pop()}};ss.Observable.registerObserver=function(a){ss.Observable._observerStack.push(a);return ss.Observable._observerRegistration};ss.Observable._captureObservers=function(a){var b=ss.Observable._observerStack,c=b.length;if(c){for(var a=a||[],d=0;d<c;d++){var j=b[d];!a.contains(j)&&a.push(j)}return a}return null};
ss.Observable._invalidateObservers=function(a){for(var b=0,c=a.length;b<c;b++)a[b].invalidateObserver()};ss.Observable.registerClass("Observable");ss.ObservableCollection=function(a){this._items=a||[];this._observers=null};ss.ObservableCollection.prototype={get_item:function(a){this._observers=ss.Observable._captureObservers(this._observers);return this._items[a]},set_item:function(a,b){this._items[a]=b;this._updated()},get_length:function(){this._observers=ss.Observable._captureObservers(this._observers);
return this._items.length},add:function(a){this._items.push(a);this._updated()},clear:function(){this._items.clear();this._updated()},contains:function(a){return this._items.contains(a)},getEnumerator:function(){this._observers=ss.Observable._captureObservers(this._observers);return this._items.getEnumerator()},indexOf:function(a){return this._items.indexOf(a)},insert:function(a,b){this._items.insert(a,b);this._updated()},remove:function(a){if(this._items.remove(a)){this._updated();return true}return false},
removeAt:function(a){this._items.removeAt(a);this._updated()},toArray:function(){return this._items},_updated:function(){var a=this._observers;if(a){this._observers=null;ss.Observable._invalidateObservers(a)}}};ss.ObservableCollection.registerClass("ObservableCollection",null,ss.IEnumerable);ss.Task=function(a){this._continuations=ss.isValue(a)?(this.status="done",null):(this.status="pending",[]);this.result=a;this.error=null};ss.Task.prototype={get_completed:function(){return this.status!="pending"},
continueWith:function(a){if(this._continuations)this._continuations.push(a);else{var b=this;setTimeout(function(){a(b)},0)}return this},done:function(a){return this.continueWith(function(b){b.status=="done"&&a(b.result)})},fail:function(a){return this.continueWith(function(b){b.status=="failed"&&a(b.error)})},then:function(a,b){return this.continueWith(function(c){c.status=="done"?a(c.result):b(c.error)})},_update:function(a,b){if(this.status=="pending"){if(b){this.error=b;this.status="failed"}else{this.result=
a;this.status="done"}var c=this._continuations;this._continuations=null;for(var d=0,j=c.length;d<j;d++)c[d](this)}}};ss.Task._join=function(a,b){function c(a){if(l.status=="pending"){g++;b?l._update(a):g==j&&l._update(true)}}function d(){l.status=="pending"&&(b?l._update(null):l._update(false))}var a=Array.toArray(a),j=a.length,h=0;if(j>1&&typeof a[0]=="number"){h=a[0];a=a.slice(1);j--}var l=new ss.Task,g=0;h!=0&&setTimeout(d,h);for(h=0;h<j;h++)a[h].continueWith(c);return l};ss.Task.all=function(){return ss.Task._join(arguments,
false)};ss.Task.any=function(){return ss.Task._join(arguments,true)};ss.Task.delay=function(a){var b=new ss.Task;setTimeout(function(){b._update(true)},a);return b};ss.Deferred=function(a){this.task=new ss.Task(a)};ss.Deferred.prototype={resolve:function(a){this.task._update(a)},reject:function(a){this.task._update(null,a||Error())}};ss.Deferred.registerClass("Deferred");ss.Task.registerClass("Task");ss.IApplication=function(){};ss.IApplication.registerInterface("IApplication");ss.IContainer=function(){};
ss.IContainer.registerInterface("IContainer");ss.IObjectFactory=function(){};ss.IObjectFactory.registerInterface("IObjectFactory");ss.IEventManager=function(){};ss.IEventManager.registerInterface("IEventManager");ss.IInitializable=function(){};ss.IInitializable.registerInterface("IInitializable")})(this);(function(){Type.registerNamespace("lt");window.lt.Leadtools$1=function(){};lt.NotifyLeadCollectionChangedAction=function(){};lt.NotifyLeadCollectionChangedAction.prototype={add:0,remove:1,replace:2,move:3,reset:4};lt.NotifyLeadCollectionChangedAction.registerEnum("lt.NotifyLeadCollectionChangedAction",!1);lt.LTDevice=function(){};lt.LTDevice.prototype={unknown:0,desktop:1,mobile:2,tablet:3};lt.LTDevice.registerEnum("lt.LTDevice",!1);lt.LTOS=function(){};lt.LTOS.prototype={unknown:0,windows:1,mac:2,
iOS:3,android:4,linux:5,blackberry:6,webOS:7,windows7:8,windows8:9};lt.LTOS.registerEnum("lt.LTOS",!1);lt.LTBrowser=function(){};lt.LTBrowser.prototype={unknown:0,internetExplorer:1,firefox:2,chrome:3,safari:4,opera:5,android:6};lt.LTBrowser.registerEnum("lt.LTBrowser",!1);lt.NotifyLeadCollectionChangedEventArgs=function(){this.$1_1=[];this.$1_2=[];lt.NotifyLeadCollectionChangedEventArgs.initializeBase(this)};lt.NotifyLeadCollectionChangedEventArgs.create=function(a){var b=new lt.NotifyLeadCollectionChangedEventArgs;
b.$1_0=a;return b};lt.NotifyLeadCollectionChangedEventArgs.createMove=function(a,b){var c=new lt.NotifyLeadCollectionChangedEventArgs;c.$1_0=3;c.$1_4=a;c.$1_3=b;return c};lt.NotifyLeadCollectionChangedEventArgs.createRemove=function(a){var b=new lt.NotifyLeadCollectionChangedEventArgs;b.$1_0=1;b.$1_4=a;b.$1_3=-1;return b};lt.NotifyLeadCollectionChangedEventArgs.createReplace=function(a){var b=new lt.NotifyLeadCollectionChangedEventArgs;b.$1_0=2;b.$1_4=a;b.$1_3=a;return b};lt.NotifyLeadCollectionChangedEventArgs.prototype=
{$1_0:0,get_action:function(){return this.$1_0},get_newItems:function(){return this.$1_1},get_oldItems:function(){return this.$1_2},$1_3:0,get_newStartingIndex:function(){return this.$1_3},$1_4:0,get_oldStartingIndex:function(){return this.$1_4}};Object.defineProperty(lt.NotifyLeadCollectionChangedEventArgs.prototype,"action",{get:lt.NotifyLeadCollectionChangedEventArgs.prototype.get_action,enumerable:!0,configurable:!0});Object.defineProperty(lt.NotifyLeadCollectionChangedEventArgs.prototype,"newItems",
{get:lt.NotifyLeadCollectionChangedEventArgs.prototype.get_newItems,enumerable:!0,configurable:!0});Object.defineProperty(lt.NotifyLeadCollectionChangedEventArgs.prototype,"oldItems",{get:lt.NotifyLeadCollectionChangedEventArgs.prototype.get_oldItems,enumerable:!0,configurable:!0});Object.defineProperty(lt.NotifyLeadCollectionChangedEventArgs.prototype,"newStartingIndex",{get:lt.NotifyLeadCollectionChangedEventArgs.prototype.get_newStartingIndex,enumerable:!0,configurable:!0});Object.defineProperty(lt.NotifyLeadCollectionChangedEventArgs.prototype,
"oldStartingIndex",{get:lt.NotifyLeadCollectionChangedEventArgs.prototype.get_oldStartingIndex,enumerable:!0,configurable:!0});lt.LeadCollection=function(){this.$0=[]};lt.LeadCollection.prototype={get_count:function(){return this.$0.length},clear:function(){this.clearItems()},remove:function(a){this.removeItem(this.indexOf(a))},add:function(a){this.insertItem(this.get_count(),a)},contains:function(a){return this.$0.contains(a)},getEnumerator:function(){return this.$0.getEnumerator()},$1:function(a,
b,c){for(var d=0,b=ss.IEnumerator.getEnumerator(b);b.moveNext();)d<c||(a[d]=b.current,d++)},toArray:function(){var a=Array(this.$0.length);this.$1(a,this.$0,0);return a},insertItem:function(a,b){var c=lt.NotifyLeadCollectionChangedEventArgs.create(0);c.get_newItems().add(b);this.$0[a]=b;this.onCollectionChanged(c)},move:function(a,b){this.moveItem(a,b)},insert:function(a,b){this.insertItem(a,b)},moveItem:function(a,b){var c=this.$0[a];this.removeItem(a);this.insertItem(b,c);this.onCollectionChanged(lt.NotifyLeadCollectionChangedEventArgs.create(3))},
onCollectionChanged:function(a){null!=this.$2&&this.$2(this,a)},removeAt:function(a){this.removeItem(a)},removeItem:function(a){var a=this.get_item(a),b=lt.NotifyLeadCollectionChangedEventArgs.create(1);b.get_newItems().add(a);this.$0.remove(a);this.onCollectionChanged(b)},setItem:function(a,b){this.$0[a]=b;this.onCollectionChanged(lt.NotifyLeadCollectionChangedEventArgs.create(2))},clearItems:function(){for(var a=lt.NotifyLeadCollectionChangedEventArgs.create(4),b=ss.IEnumerator.getEnumerator(this.$0);b.moveNext();){var c=
b.current;a.get_newItems().add(c)}this.$0.clear();this.onCollectionChanged(a)},indexOf:function(a){return this.$0.indexOf(a)},add_collectionChanged:function(a){this.$2=ss.Delegate.combine(this.$2,a)},remove_collectionChanged:function(a){this.$2=ss.Delegate.remove(this.$2,a)},$2_handler_get:function(){null==this.$2_handler&&(this.$2_handler=ss.EventHandler.create(this,this.add_collectionChanged,this.remove_collectionChanged));return this.$2_handler},$2:null,$2_handler:null,get_item:function(a){return this.$0[a]},
set_item:function(a,b){return this.$0[a]=b},item:function(a,b){return void 0===b?this.get_item(a):this.set_item(a,b)}};Object.defineProperty(lt.LeadCollection.prototype,"count",{get:lt.LeadCollection.prototype.get_count,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadCollection.prototype,"collectionChanged",{get:lt.LeadCollection.prototype.$2_handler_get,enumerable:!0,configurable:!0});lt.LeadEventArgs=function(){};lt.LeadEventArgs.addToEvent=function(a,b,c){a["__"+b]=ss.Delegate.combine(a["__"+
b],c)};lt.LeadEventArgs.removeFromEvent=function(a,b,c){a["__"+b]=ss.Delegate.remove(a["__"+b],c)};lt.LeadEvent=function(){};lt.LeadEvent.create=function(a,b){if(String.isNullOrWhiteSpace(b))throw Error("'eventName' cannot be null or empty");if(null==a)throw Error("'target' cannot be null");var c=b+"_leadEventHandler",d=b+"_leadEvent";if(a[c]||a[d])throw Error("Event '"+d+"' already defined");a[c]=null;a[d]=ss.EventHandler.create(a,function(b){a[c]=ss.Delegate.combine(a[c],b);a[d].handler=a[c]},function(b){a[c]=
ss.Delegate.remove(a[c],b);a[d].handler=a[c]});a[d].invoke=function(a,b){null!=this.handler&&this.handler(a,b)};return a[d]};lt.LeadEvent.prototype={invoke:function(a,b){null!=this.handler&&this.handler(a,b)}};lt.ImageProcessingProgressEventArgs=function(){lt.ImageProcessingProgressEventArgs.initializeBase(this)};lt.ImageProcessingProgressEventArgs.create=function(a){var b=new lt.ImageProcessingProgressEventArgs;b.$1_0=a;b.$1_1=!1;return b};lt.ImageProcessingProgressEventArgs.prototype={$1_0:0,get_percentage:function(){return this.$1_0},
$1_1:!1,get_cancel:function(){return this.$1_1},set_cancel:function(a){return this.$1_1=a}};Object.defineProperty(lt.ImageProcessingProgressEventArgs.prototype,"percentage",{get:lt.ImageProcessingProgressEventArgs.prototype.get_percentage,enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessingProgressEventArgs.prototype,"cancel",{get:lt.ImageProcessingProgressEventArgs.prototype.get_cancel,set:lt.ImageProcessingProgressEventArgs.prototype.set_cancel,enumerable:!0,configurable:!0});
lt.ImageProcessingCompletedEventArgs=function(){lt.ImageProcessingCompletedEventArgs.initializeBase(this)};lt.ImageProcessingCompletedEventArgs.create=function(a,b){var c=new lt.ImageProcessingCompletedEventArgs;c.$1_0=a;c.$1_1=b;return c};lt.ImageProcessingCompletedEventArgs.prototype={$1_0:null,get_imageData:function(){return this.$1_0},$1_1:null,get_results:function(){return this.$1_1}};Object.defineProperty(lt.ImageProcessingCompletedEventArgs.prototype,"imageData",{get:lt.ImageProcessingCompletedEventArgs.prototype.get_imageData,
enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessingCompletedEventArgs.prototype,"results",{get:lt.ImageProcessingCompletedEventArgs.prototype.get_results,enumerable:!0,configurable:!0});lt.ImageProcessingErrorEventArgs=function(){lt.ImageProcessingErrorEventArgs.initializeBase(this)};lt.ImageProcessingErrorEventArgs.create=function(a){var b=new lt.ImageProcessingErrorEventArgs;b.$1_0=a;return b};lt.ImageProcessingErrorEventArgs.prototype={$1_0:null,get_error:function(){return this.$1_0}};
Object.defineProperty(lt.ImageProcessingErrorEventArgs.prototype,"error",{get:lt.ImageProcessingErrorEventArgs.prototype.get_error,enumerable:!0,configurable:!0});lt.ImageProcessing=function(){this.$3={}};lt.ImageProcessing.$D=function(a){var b=a.lastIndexOf("/");-1!==b&&(a=a.substr(b+1));b=a.lastIndexOf("\\");-1!==b&&(a=a.substr(b+1));return a=a.substr(0,a.length-3)};lt.ImageProcessing.prototype={$0:null,get_jsFilePath:function(){return this.$0},set_jsFilePath:function(a){return this.$0=a},$1:null,
get_command:function(){return this.$1},set_command:function(a){return this.$1=a},$2:null,get_imageData:function(){return this.$2},set_imageData:function(a){return this.$2=a},$3:null,get_arguments:function(){return this.$3},add_progress:function(a){this.$4=ss.Delegate.combine(this.$4,a)},remove_progress:function(a){this.$4=ss.Delegate.remove(this.$4,a)},$4_handler_get:function(){null==this.$4_handler&&(this.$4_handler=ss.EventHandler.create(this,this.add_progress,this.remove_progress));return this.$4_handler},
$4:null,$4_handler:null,add_completed:function(a){this.$5=ss.Delegate.combine(this.$5,a)},remove_completed:function(a){this.$5=ss.Delegate.remove(this.$5,a)},$5_handler_get:function(){null==this.$5_handler&&(this.$5_handler=ss.EventHandler.create(this,this.add_completed,this.remove_completed));return this.$5_handler},$5:null,$5_handler:null,add_error:function(a){this.$6=ss.Delegate.combine(this.$6,a)},remove_error:function(a){this.$6=ss.Delegate.remove(this.$6,a)},$6_handler_get:function(){null==
this.$6_handler&&(this.$6_handler=ss.EventHandler.create(this,this.add_error,this.remove_error));return this.$6_handler},$6:null,$6_handler:null,$7:!1,get_isRunning:function(){return this.$7},$8:null,$9:null,$A:null,$B:!1,abort:function(){this.$7&&(this.$B=!0,null!=this.$A&&(this.$C(this.$A),this.$A.terminate(),this.$A=null),this.$7=!1)},$C:function(a){null!=a&&(null!=this.$8&&this.$A.removeEventListener("message",this.$8,!1),this.$8=null,null!=this.$9&&this.$A.removeEventListener("error",this.$9,
!1),this.$9=null)},run:function(){if(null==this.$1)throw Error("'Command' must be set before calling this method");if(null==this.$2)throw Error("'ImageData' must be set before calling this method");if(null==this.$0)throw Error("'JSFilePath' must be set before calling this method");this.$B=this.$7=!1;var a=this.$A=null,b=null,c=null,d=!1,e=null,i=null;if(lt.LTHelper.supportsWebWorker)b=new Worker(this.$0),c=b.postMessage;else{var k=lt.ImageProcessing.$D(this.$0).replaceAll(".","_")+"_Main",c=window[k];
if(null==c){this.$7=!0;lt.LTHelper.loadJS(this.$0,ss.Delegate.create(this,function(){this.$7=!1;c=window[k];d=null!=this.$4;e=ss.Delegate.create(this,function(a){var a=a.data?a.data:a,c=a.status;"Progress"===c&&d?(null!=this.$4&&(c=lt.ImageProcessingProgressEventArgs.create(a.percentage),this.$4(this,c),c.get_cancel()&&(this.$B=!0)),this.$B&&(null!=b?this.abort():a.abort=!0)):"Completed"===c&&(c=a.imageData,this.$C(this.$A),null!=this.$5&&this.$5(this,lt.ImageProcessingCompletedEventArgs.create(c,
a)),this.$A=null,this.$7=!1)});i={imageData:this.$2,callback:null==b?e:null,useProgress:d,command:this.$1};a=this.$3;if(0<Object.getKeyCount(a))for(var f=ss.IEnumerator.getEnumerator(Object.keys(a));f.moveNext();){var g=f.current;i[g]=a[g]}this.$7=!0;this.$B=!1;this.$A=b;if(null==c)throw Error("Could not find Image Processing main entry function:"+k);c(i)}));return}}var d=null!=this.$4,e=ss.Delegate.create(this,function(a){var a=a.data?a.data:a,c=a.status;"Progress"===c&&d?(null!=this.$4&&(c=lt.ImageProcessingProgressEventArgs.create(a.percentage),
this.$4(this,c),c.get_cancel()&&(this.$B=!0)),this.$B&&(null!=b?this.abort():a.abort=!0)):"Completed"===c&&(c=a.imageData,this.$C(this.$A),null!=this.$5&&this.$5(this,lt.ImageProcessingCompletedEventArgs.create(c,a)),this.$A=null,this.$7=!1)}),f=null;null!=b&&(f=ss.Delegate.create(this,function(a){null!=this.$6&&(a=!ss.isNullOrUndefined(a.message)?a.message:"Could not run image processing command. Make sure the library path is set",this.$6(this,lt.ImageProcessingErrorEventArgs.create(Error(a))));
this.abort()}));i={imageData:this.$2,callback:null==b?e:null,useProgress:d,command:this.$1};a=this.$3;if(0<Object.getKeyCount(a))for(var j=ss.IEnumerator.getEnumerator(Object.keys(a));j.moveNext();){var h=j.current;i[h]=a[h]}4===lt.LTHelper.browser&&(i.width=this.$2.width,i.height=this.$2.height);this.$7=!0;this.$B=!1;this.$A=b;null!=b?(this.$8=e,this.$9=f,b.addEventListener("message",e,!1),b.postMessage(i),b.addEventListener("error",f,!1)):c(i)}};Object.defineProperty(lt.ImageProcessing.prototype,
"jsFilePath",{get:lt.ImageProcessing.prototype.get_jsFilePath,set:lt.ImageProcessing.prototype.set_jsFilePath,enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessing.prototype,"command",{get:lt.ImageProcessing.prototype.get_command,set:lt.ImageProcessing.prototype.set_command,enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessing.prototype,"imageData",{get:lt.ImageProcessing.prototype.get_imageData,set:lt.ImageProcessing.prototype.set_imageData,enumerable:!0,configurable:!0});
Object.defineProperty(lt.ImageProcessing.prototype,"arguments",{get:lt.ImageProcessing.prototype.get_arguments,enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessing.prototype,"progress",{get:lt.ImageProcessing.prototype.$4_handler_get,enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessing.prototype,"completed",{get:lt.ImageProcessing.prototype.$5_handler_get,enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessing.prototype,"error",{get:lt.ImageProcessing.prototype.$6_handler_get,
enumerable:!0,configurable:!0});Object.defineProperty(lt.ImageProcessing.prototype,"isRunning",{get:lt.ImageProcessing.prototype.get_isRunning,enumerable:!0,configurable:!0});lt.LeadLengthD=function(){};lt.LeadLengthD.create=function(a){var b=new lt.LeadLengthD;b.$0=a;return b};lt.LeadLengthD.equals=function(a,b){return lt.LeadDoubleTools.areClose(a.get_value(),b.get_value())};lt.LeadLengthD.prototype={$0:0,clone:function(){return lt.LeadLengthD.create(this.$0)},get_value:function(){return this.$0},
set_value:function(a){return this.$0=a},toString:function(){return this.$0.toString()}};Object.defineProperty(lt.LeadLengthD.prototype,"value",{get:lt.LeadLengthD.prototype.get_value,set:lt.LeadLengthD.prototype.set_value,enumerable:!0,configurable:!0});lt.LeadDoubleTools=function(){};lt.LeadDoubleTools.areClose=function(a,b){if(a===b)return!0;var c=2.22044604925031E-16*(Math.abs(a)+Math.abs(b)+10),d=a-b;return-c<d&&c>d};lt.LeadDoubleTools.lessThan=function(a,b){return a<b&&!lt.LeadDoubleTools.areClose(a,
b)};lt.LeadDoubleTools.greaterThan=function(a,b){return a>b&&!lt.LeadDoubleTools.areClose(a,b)};lt.LeadDoubleTools.lessThanOrClose=function(a,b){return a<b||lt.LeadDoubleTools.areClose(a,b)};lt.LeadDoubleTools.greaterThanOrClose=function(a,b){return a>b||lt.LeadDoubleTools.areClose(a,b)};lt.LeadDoubleTools.isOne=function(a){return 2.22044604925031E-15>Math.abs(a-1)};lt.LeadDoubleTools.isZero=function(a){return 2.22044604925031E-15>Math.abs(a)};lt.LeadDoubleTools.areClosePoints=function(a,b){return lt.LeadDoubleTools.areClose(a.get_x(),
b.get_x())&&lt.LeadDoubleTools.areClose(a.get_y(),b.get_y())};lt.LeadDoubleTools.areCloseSizes=function(a,b){return lt.LeadDoubleTools.areClose(a.get_width(),b.get_width())&&lt.LeadDoubleTools.areClose(a.get_height(),b.get_height())};lt.LeadDoubleTools.areCloseRects=function(a,b){return a.get_isEmpty()?b.get_isEmpty():!b.get_isEmpty()&&lt.LeadDoubleTools.areClose(a.get_x(),b.get_x())&&lt.LeadDoubleTools.areClose(a.get_y(),b.get_y())&&lt.LeadDoubleTools.areClose(a.get_height(),b.get_height())&&lt.LeadDoubleTools.areClose(a.get_width(),
b.get_width())};lt.LeadDoubleTools.isBetweenZeroAndOne=function(a){return lt.LeadDoubleTools.greaterThanOrClose(a,0)&&lt.LeadDoubleTools.lessThanOrClose(a,1)};lt.LeadDoubleTools.doubleToInt=function(a){return 0>=a?parseInt(a-0.5):parseInt(a+0.5)};lt.LeadDoubleTools.rectHasNaN=function(a){return lt.LeadDoubleTools.isNaN(a.get_x())||lt.LeadDoubleTools.isNaN(a.get_y())||lt.LeadDoubleTools.isNaN(a.get_height())||lt.LeadDoubleTools.isNaN(a.get_width())};lt.LeadDoubleTools.isNaN=function(a){return isNaN(a)};
lt.LeadDoubleTools.isInfinity=function(a){return a===lt.LeadDoubleTools.positiveInfinity||a===lt.LeadDoubleTools.negativeInfinity};lt.LeadDoubleTools.normalizeAngle=function(a){for(;360<a;)a-=360;for(;0>a;)a+=360;return a};lt.LeadMatrix=function(){};lt.LeadMatrix.create=function(a,b,c,d,e,i){var k=new lt.LeadMatrix;k.$3=a;k.$4=b;k.$5=c;k.$6=d;k.$7=e;k.$8=i;k.$9=4;k.$A=0;k.$16();return k};lt.LeadMatrix.get_identity=function(){return lt.LeadMatrix.$1.clone()};lt.LeadMatrix.multiply=function(a,b){return lt.Leadtools$2.$1(a,
b)};lt.LeadMatrix.$E=function(a){return lt.LeadMatrix.$F(a,0,0)};lt.LeadMatrix.$F=function(a,b,c){var d=new lt.LeadMatrix,e=Math.sin(a),a=Math.cos(a);d.$15(a,e,-e,a,b*(1-a)+c*e,c*(1-a)-b*e,4);return d};lt.LeadMatrix.$10=function(a,b,c,d){var e=new lt.LeadMatrix;e.$15(a,0,0,b,c-a*c,d-b*d,3);return e};lt.LeadMatrix.$11=function(a,b){var c=new lt.LeadMatrix;c.$15(a,0,0,b,0,0,2);return c};lt.LeadMatrix.$12=function(a,b){var c=new lt.LeadMatrix;c.$15(1,Math.tan(b),Math.tan(a),1,0,0,4);return c};lt.LeadMatrix.$13=
function(a,b){var c=new lt.LeadMatrix;c.$15(1,0,0,1,a,b,1);return c};lt.LeadMatrix.$14=function(){var a=new lt.LeadMatrix;a.$15(1,0,0,1,0,0,0);return a};lt.LeadMatrix.equals=function(a,b){return a.get_$C()||b.get_$C()?a.get_isIdentity()===b.get_isIdentity():a.get_m11()===b.get_m11()&&a.get_m12()===b.get_m12()&&a.get_m21()===b.get_m21()&&a.get_m22()===b.get_m22()&&a.get_offsetX()===b.get_offsetX()&&a.get_offsetY()===b.get_offsetY()};lt.LeadMatrix.prototype={$3:0,$4:0,$5:0,$6:0,$7:0,$8:0,$9:0,$A:0,
clone:function(){var a=new lt.LeadMatrix;a.$3=this.$3;a.$4=this.$4;a.$5=this.$5;a.$6=this.$6;a.$7=this.$7;a.$8=this.$8;a.$9=this.$9;a.$A=0;return a},$B:function(a){this.$3=a.$3;this.$4=a.$4;this.$5=a.$5;this.$6=a.$6;this.$7=a.$7;this.$8=a.$8;this.$9=a.$9;this.$A=0},get_isIdentity:function(){return!this.$9||1===this.$3&&0===this.$4&&0===this.$5&&1===this.$6&&0===this.$7&&0===this.$8},get_determinant:function(){switch(this.$9){case 0:case 1:return 1;case 2:case 3:return this.$3*this.$6;default:return this.$3*
this.$6-this.$4*this.$5}},get_hasInverse:function(){return!lt.LeadDoubleTools.isZero(this.get_determinant())},get_m11:function(){return!this.$9?1:this.$3},set_m11:function(a){if(this.$9)return this.$3=a,4!==this.$9&&(this.$9|=2),a;this.$15(a,0,0,1,0,0,2)},get_m12:function(){return!this.$9?0:this.$4},set_m12:function(a){if(this.$9)return this.$4=a,this.$9=4,a;this.$15(1,a,0,1,0,0,4)},get_m21:function(){return!this.$9?0:this.$5},set_m21:function(a){if(this.$9)return this.$5=a,this.$9=4,a;this.$15(1,
0,a,1,0,0,4)},get_m22:function(){return!this.$9?1:this.$6},set_m22:function(a){if(this.$9)return this.$6=a,4!==this.$9&&(this.$9|=2),a;this.$15(1,0,0,a,0,0,2)},get_offsetX:function(){return!this.$9?0:this.$7},set_offsetX:function(a){if(this.$9)return this.$7=a,4!==this.$9&&(this.$9|=1),a;this.$15(1,0,0,1,a,0,1)},get_offsetY:function(){return!this.$9?0:this.$8},set_offsetY:function(a){if(this.$9)return this.$8=a,4!==this.$9&&(this.$9|=1),a;this.$15(1,0,0,1,0,a,1)},get_$C:function(){return!this.$9},
setIdentity:function(){this.$9=0},append:function(a){this.$B(lt.Leadtools$2.$1(this,a))},prepend:function(a){this.$B(lt.Leadtools$2.$1(a,this))},rotate:function(a){a=lt.LeadDoubleTools.normalizeAngle(a);this.$B(lt.Leadtools$2.$1(this,lt.LeadMatrix.$E(0.0174532925199433*a)))},rotatePrepend:function(a){a=lt.LeadDoubleTools.normalizeAngle(a);this.$B(lt.Leadtools$2.$1(lt.LeadMatrix.$E(0.0174532925199433*a),this))},rotateAt:function(a,b,c){a=lt.LeadDoubleTools.normalizeAngle(a);this.$B(lt.Leadtools$2.$1(this,
lt.LeadMatrix.$F(0.0174532925199433*a,b,c)))},rotateAtPrepend:function(a,b,c){a=lt.LeadDoubleTools.normalizeAngle(a);this.$B(lt.Leadtools$2.$1(lt.LeadMatrix.$F(0.0174532925199433*a,b,c),this))},scale:function(a,b){this.$B(lt.Leadtools$2.$1(this,lt.LeadMatrix.$11(a,b)))},scalePrepend:function(a,b){this.$B(lt.Leadtools$2.$1(lt.LeadMatrix.$11(a,b),this))},scaleAt:function(a,b,c,d){this.$B(lt.Leadtools$2.$1(this,lt.LeadMatrix.$10(a,b,c,d)))},scaleAtPrepend:function(a,b,c,d){this.$B(lt.Leadtools$2.$1(lt.LeadMatrix.$10(a,
b,c,d),this))},skew:function(a,b){a=lt.LeadDoubleTools.normalizeAngle(a);b=lt.LeadDoubleTools.normalizeAngle(b);this.$B(lt.Leadtools$2.$1(this,lt.LeadMatrix.$12(0.0174532925199433*a,0.0174532925199433*b)))},skewPrepend:function(a,b){a=lt.LeadDoubleTools.normalizeAngle(a);b=lt.LeadDoubleTools.normalizeAngle(b);this.$B(lt.Leadtools$2.$1(lt.LeadMatrix.$12(0.0174532925199433*a,0.0174532925199433*b),this))},translate:function(a,b){this.$9?4===this.$9?(this.$7+=a,this.$8+=b):(this.$7+=a,this.$8+=b,this.$9|=
1):this.$15(1,0,0,1,a,b,1)},translatePrepend:function(a,b){this.$B(lt.Leadtools$2.$1(lt.LeadMatrix.$13(a,b),this))},transformPoint:function(a){return this.$D(a,!1)},transformVector:function(a){return this.$D(a,!0)},transformRect:function(a){return lt.Leadtools$2.$0(a,this)},transformPoints:function(a){if(null!=a)for(var b=0;b<a.length;b++)a[b]=this.$D(a[b],!1)},invert:function(){var a=this.get_determinant();if(lt.LeadDoubleTools.isZero(a))throw Error("Transform is not invertible");switch(this.$9){case 0:break;
case 1:this.$7=-this.$7;this.$8=-this.$8;break;case 2:this.$3=1/this.$3;this.$6=1/this.$6;break;case 3:this.$3=1/this.$3;this.$6=1/this.$6;this.$7=-this.$7*this.$3;this.$8=-this.$8*this.$6;break;default:a=1/a,this.$15(this.$6*a,-this.$4*a,-this.$5*a,this.$3*a,(this.$5*this.$8-this.$7*this.$6)*a,(this.$7*this.$4-this.$3*this.$8)*a,4)}},$D:function(a,b){var c=a.clone();switch(this.$9){case 0:return c;case 1:return b||(c._x+=this.$7,c._y+=this.$8),c;case 2:return c._x*=this.$3,c._y*=this.$6,c;case 3:return c._x*=
this.$3,c._y*=this.$6,b||(c._x+=this.$7,c._y+=this.$8),c;default:var d=c._y*this.$5,e=c._x*this.$4;b||(d+=this.$7,e+=this.$8);c._x*=this.$3;c._x+=d;c._y*=this.$6;c._y+=e;return c}},$15:function(a,b,c,d,e,i,k){this.$3=a;this.$4=b;this.$5=c;this.$6=d;this.$7=e;this.$8=i;this.$9=k},$16:function(){this.$9=0;if(0!==this.$5||0!==this.$4)this.$9=4;else{if(1!==this.$3||1!==this.$6)this.$9=2;if(0!==this.$7||0!==this.$8)this.$9|=1;this.$9&3||(this.$9=0)}},toString:function(){return this.get_isIdentity()?"Identity":
String.format("{0},{1},{2},{3},{4},{5}",this.$3,this.$4,this.$5,this.$6,this.$7,this.$8)}};Object.defineProperty(lt.LeadMatrix,"identity",{get:lt.LeadMatrix.get_identity,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"isIdentity",{get:lt.LeadMatrix.prototype.get_isIdentity,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"determinant",{get:lt.LeadMatrix.prototype.get_determinant,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,
"hasInverse",{get:lt.LeadMatrix.prototype.get_hasInverse,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"m11",{get:lt.LeadMatrix.prototype.get_m11,set:lt.LeadMatrix.prototype.set_m11,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"m12",{get:lt.LeadMatrix.prototype.get_m12,set:lt.LeadMatrix.prototype.set_m12,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"m21",{get:lt.LeadMatrix.prototype.get_m21,set:lt.LeadMatrix.prototype.set_m21,
enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"m22",{get:lt.LeadMatrix.prototype.get_m22,set:lt.LeadMatrix.prototype.set_m22,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"offsetX",{get:lt.LeadMatrix.prototype.get_offsetX,set:lt.LeadMatrix.prototype.set_offsetX,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadMatrix.prototype,"offsetY",{get:lt.LeadMatrix.prototype.get_offsetY,set:lt.LeadMatrix.prototype.set_offsetY,enumerable:!0,
configurable:!0});lt.Leadtools$2=function(){};lt.Leadtools$2.$0=function(a,b){var c=a.clone();if(a.get_isEmpty())return c;var d=b.$9;if(!d)return c;if(d&2&&(c._x*=b.$3,c._y*=b.$6,c.$3*=b.$3,c.$4*=b.$6,0>c.$3&&(c._x+=c.$3,c.$3=-c.$3),0>c.$4))c._y+=c.$4,c.$4=-c.$4;d&1&&(c._x+=b.$7,c._y+=b.$8);if(4===d){var d=b.transformPoint(c.get_topLeft()),e=b.transformPoint(c.get_topRight()),i=b.transformPoint(c.get_bottomRight()),k=b.transformPoint(c.get_bottomLeft());c._x=Math.min(Math.min(d.get_x(),e.get_x()),
Math.min(i.get_x(),k.get_x()));c._y=Math.min(Math.min(d.get_y(),e.get_y()),Math.min(i.get_y(),k.get_y()));c.$3=Math.max(Math.max(d.get_x(),e.get_x()),Math.max(i.get_x(),k.get_x()))-c._x;c.$4=Math.max(Math.max(d.get_y(),e.get_y()),Math.max(i.get_y(),k.get_y()))-c._y}return c};lt.Leadtools$2.$1=function(a,b){var c=a.$9,d=b.$9,e=a.clone();if(!d)return e;if(!c)return e=b.clone();if(1===d)return e.$7+=b.$7,e.$8+=b.$8,4!==c&&(e.$9|=1),e;if(1!==c){d|=c<<4;switch(d){case 34:return e.$3*=b.$3,e.$6*=b.$6,e;
case 35:return e.$3*=b.$3,e.$6*=b.$6,e.$7=b.$7,e.$8=b.$8,e.$9=3,e;case 36:break;default:switch(d){case 50:return e.$3*=b.$3,e.$6*=b.$6,e.$7*=b.$3,e.$8*=b.$6,e;case 51:return e.$3*=b.$3,e.$6*=b.$6,e.$7=b.$3*e.$7+b.$7,e.$8=b.$6*e.$8+b.$8,e;case 52:break;default:switch(d){case 66:case 67:case 68:break;default:return e}}}return e=lt.LeadMatrix.create(a.$3*b.$3+a.$4*b.$5,a.$3*b.$4+a.$4*b.$6,a.$5*b.$3+a.$6*b.$5,a.$5*b.$4+a.$6*b.$6,a.$7*b.$3+a.$8*b.$5+b.$7,a.$7*b.$4+a.$8*b.$6+b.$8)}var c=a.$7,i=a.$8,e=b.clone();
e.$7=c*b.$3+i*b.$5+b.$7;e.$8=c*b.$4+i*b.$6+b.$8;if(4===d)return e.$9=4,e;e.$9=3;return e};lt.LeadPointD=function(){};lt.LeadPointD.get_empty=function(){return lt.LeadPointD.$1};lt.LeadPointD.create=function(a,b){var c=new lt.LeadPointD;c._x=a;c._y=b;return c};lt.LeadPointD.equals=function(a,b){return a.get_isEmpty()?b.get_isEmpty():lt.LeadDoubleTools.areClosePoints(a,b)};lt.LeadPointD.$2=function(){var a=new lt.LeadPointD;a._x=lt.LeadDoubleTools.naN;a._y=lt.LeadDoubleTools.naN;return a};lt.LeadPointD.prototype=
{_x:0,_y:0,get_isEmpty:function(){return lt.LeadDoubleTools.isNaN(this._x)},clone:function(){return this.get_isEmpty()?lt.LeadPointD.$1:lt.LeadPointD.create(this._x,this._y)},get_x:function(){return this._x},set_x:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty LeadPointD");return this._x=a},get_y:function(){return this._y},set_y:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty LeadPointD");return this._y=a},toString:function(){return this.get_isEmpty()?"Empty":
String.format("{0},{1}",this._x,this._y)}};Object.defineProperty(lt.LeadPointD,"empty",{get:lt.LeadPointD.get_empty,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadPointD.prototype,"isEmpty",{get:lt.LeadPointD.prototype.get_isEmpty,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadPointD.prototype,"x",{get:lt.LeadPointD.prototype.get_x,set:lt.LeadPointD.prototype.set_x,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadPointD.prototype,"y",{get:lt.LeadPointD.prototype.get_y,
set:lt.LeadPointD.prototype.set_y,enumerable:!0,configurable:!0});lt.LeadRectD=function(){};lt.LeadRectD.create=function(a,b,c,d){if(0>c||0>d)throw Error("Width or Height of 'LeadRectD' cannot be negative");var e=new lt.LeadRectD;e._x=a;e._y=b;e.$3=c;e.$4=d;return e};lt.LeadRectD.fromLTRB=function(a,b,c,d){var e;c>=a?(e=a,a=c-a):(e=c,a-=c);d>=b?(c=b,b=d-b):(c=d,b-=d);return lt.LeadRectD.create(e,c,a,b)};lt.LeadRectD.get_empty=function(){return lt.LeadRectD.$2};lt.LeadRectD.equals=function(a,b){return a.get_isEmpty()?
b.get_isEmpty():lt.LeadDoubleTools.areCloseRects(a,b)};lt.LeadRectD.intersectRects=function(a,b){a.intersect(b);return a};lt.LeadRectD.unionRects=function(a,b){if(a.get_isEmpty())return b.get_isEmpty()?lt.LeadRectD.get_empty():b.clone();if(b.get_isEmpty())return a.get_isEmpty()?lt.LeadRectD.get_empty():a.clone();a.union(b);return a};lt.LeadRectD.inflateRect=function(a,b,c){a.inflate(b,c);return a};lt.LeadRectD.$7=function(){var a=new lt.LeadRectD;a._x=lt.LeadDoubleTools.naN;a._y=lt.LeadDoubleTools.naN;
a.$3=lt.LeadDoubleTools.naN;a.$4=lt.LeadDoubleTools.naN;return a};lt.LeadRectD.prototype={_x:0,_y:0,$3:0,$4:0,clone:function(){var a=new lt.LeadRectD;a._x=this._x;a._y=this._y;a.$3=this.$3;a.$4=this.$4;return a},$5:function(a){this._x=a._x;this._y=a._y;this.$3=a.$3;this.$4=a.$4},get_isEmpty:function(){return lt.LeadDoubleTools.isNaN(this.$3)},get_location:function(){return lt.LeadPointD.create(this._x,this._y)},set_location:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");
this._x=a._x;this._y=a._y;return a},get_size:function(){return this.get_isEmpty()?lt.LeadSizeD.get_empty():lt.LeadSizeD.create(this.$3,this.$4)},set_size:function(a){if(a.get_isEmpty())this.$5(lt.LeadRectD.$2);else{if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");this.$3=a.$3;this.$4=a.$4;return a}},get_x:function(){return this._x},set_x:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");return this._x=a},get_y:function(){return this._y},set_y:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");
return this._y=a},get_width:function(){return this.$3},set_width:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");if(0>a)throw Error("Width or Height of 'LeadRectD' cannot be negative");return this.$3=a},get_height:function(){return this.$4},set_height:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");if(0>a)throw Error("Width or Height of 'LeadRectD' cannot be negative");return this.$4=a},get_left:function(){return this._x},get_top:function(){return this._y},
get_right:function(){return this.get_isEmpty()?-1:this._x+this.$3},get_bottom:function(){return this.get_isEmpty()?-1:this._y+this.$4},get_topLeft:function(){return lt.LeadPointD.create(this.get_left(),this.get_top())},get_topRight:function(){return lt.LeadPointD.create(this.get_right(),this.get_top())},get_bottomLeft:function(){return lt.LeadPointD.create(this.get_left(),this.get_bottom())},get_bottomRight:function(){return lt.LeadPointD.create(this.get_right(),this.get_bottom())},toString:function(){return this.get_isEmpty()?
"Empty":String.format("{0},{1},{2},{3}",this._x,this._y,this.$3,this.$4)},containsPoint:function(a){return this.contains(a._x,a._y)},contains:function(a,b){return!this.get_isEmpty()&&this.$6(a,b)},containsRect:function(a){return!this.get_isEmpty()&&!a.get_isEmpty()&&this._x<=a._x&&this._y<=a._y&&this._x+this.$3>=a._x+a.$3&&this._y+this.$4>=a._y+a.$4},intersectsWith:function(a){return!this.get_isEmpty()&&!a.get_isEmpty()&&a.get_left()<=this.get_right()&&a.get_right()>=this.get_left()&&a.get_top()<=
this.get_bottom()&&a.get_bottom()>=this.get_top()},intersect:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");if(this.intersectsWith(a)){var b=Math.max(this.get_left(),a.get_left()),c=Math.max(this.get_top(),a.get_top());this.$3=Math.max(Math.min(this.get_right(),a.get_right())-b,0);this.$4=Math.max(Math.min(this.get_bottom(),a.get_bottom())-c,0);this._x=b;this._y=c}else this.$5(lt.LeadRectD.$2)},union:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");
if(!a.get_isEmpty()){var b=Math.min(this.get_left(),a.get_left()),c=Math.min(this.get_top(),a.get_top());if(-1===a.get_width()||-1===this.get_width())this.$3=-1;else{var d=Math.max(this.get_right(),a.get_right());this.$3=Math.max(d-b,0)}-1===a.get_height()||-1===this.get_height()?this.$4=-1:(a=Math.max(this.get_bottom(),a.get_bottom()),this.$4=Math.max(a-c,0));this._x=b;this._y=c}},offset:function(a,b){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");this._x+=a;this._y+=b},inflate:function(a,
b){if(this.get_isEmpty())throw Error("Cannot modify empty 'LeadRectD'");this._x-=a;this._y-=b;this.$3+=a;this.$3+=a;this.$4+=b;this.$4+=b;(0>this.$3||0>this.$4)&&this.$5(lt.LeadRectD.$2)},scale:function(a,b){if(!this.get_isEmpty()&&(this._x*=a,this._y*=b,this.$3*=a,this.$4*=b,0>a&&(this._x+=this.$3,this.$3*=-1),0>b))this._y+=this.$4,this.$4*=-1},$6:function(a,b){return a>=this._x&&a-this.$3<=this._x&&b>=this._y&&b-this.$4<=this._y}};Object.defineProperty(lt.LeadRectD,"empty",{get:lt.LeadRectD.get_empty,
enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"isEmpty",{get:lt.LeadRectD.prototype.get_isEmpty,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"location",{get:lt.LeadRectD.prototype.get_location,set:lt.LeadRectD.prototype.set_location,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"size",{get:lt.LeadRectD.prototype.get_size,set:lt.LeadRectD.prototype.set_size,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,
"x",{get:lt.LeadRectD.prototype.get_x,set:lt.LeadRectD.prototype.set_x,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"y",{get:lt.LeadRectD.prototype.get_y,set:lt.LeadRectD.prototype.set_y,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"width",{get:lt.LeadRectD.prototype.get_width,set:lt.LeadRectD.prototype.set_width,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"height",{get:lt.LeadRectD.prototype.get_height,
set:lt.LeadRectD.prototype.set_height,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"left",{get:lt.LeadRectD.prototype.get_left,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"top",{get:lt.LeadRectD.prototype.get_top,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"right",{get:lt.LeadRectD.prototype.get_right,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"bottom",{get:lt.LeadRectD.prototype.get_bottom,
enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"topLeft",{get:lt.LeadRectD.prototype.get_topLeft,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"topRight",{get:lt.LeadRectD.prototype.get_topRight,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"bottomLeft",{get:lt.LeadRectD.prototype.get_bottomLeft,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadRectD.prototype,"bottomRight",{get:lt.LeadRectD.prototype.get_bottomRight,
enumerable:!0,configurable:!0});lt.LeadSizeD=function(){};lt.LeadSizeD.create=function(a,b){if(0>a||0>b)throw Error("Width or Height of LeadSizeD cannot be negative");var c=new lt.LeadSizeD;c.$3=a;c.$4=b;return c};lt.LeadSizeD.get_empty=function(){return lt.LeadSizeD.$2};lt.LeadSizeD.equals=function(a,b){return a.get_isEmpty()?b.get_isEmpty():lt.LeadDoubleTools.areCloseSizes(a,b)};lt.LeadSizeD.$5=function(){var a=new lt.LeadSizeD;a.$3=lt.LeadDoubleTools.naN;a.$4=lt.LeadDoubleTools.naN;return a};lt.LeadSizeD.prototype=
{$3:0,$4:0,clone:function(){var a=new lt.LeadSizeD;a.$3=this.$3;a.$4=this.$4;return a},get_isEmpty:function(){return lt.LeadDoubleTools.isNaN(this.$3)},get_width:function(){return this.$3},set_width:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty LeadSizeD");if(0>a)throw Error("Width or Height of LeadSizeD cannot be negative");return this.$3=a},get_height:function(){return this.$4},set_height:function(a){if(this.get_isEmpty())throw Error("Cannot modify empty LeadSizeD");if(0>a)throw Error("Width or Height of LeadSizeD cannot be negative");
return this.$4=a},toString:function(){return this.get_isEmpty()?"Empty":String.format("{0},{1}",this.$3,this.$4)}};Object.defineProperty(lt.LeadSizeD,"empty",{get:lt.LeadSizeD.get_empty,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadSizeD.prototype,"isEmpty",{get:lt.LeadSizeD.prototype.get_isEmpty,enumerable:!0,configurable:!0});Object.defineProperty(lt.LeadSizeD.prototype,"width",{get:lt.LeadSizeD.prototype.get_width,set:lt.LeadSizeD.prototype.set_width,enumerable:!0,configurable:!0});
Object.defineProperty(lt.LeadSizeD.prototype,"height",{get:lt.LeadSizeD.prototype.get_height,set:lt.LeadSizeD.prototype.set_height,enumerable:!0,configurable:!0});lt.LTHelper=function(){};lt.LTHelper.$0=function(a,b){for(var c=0;c<b.length;c++)if(-1!==a.indexOf(b[c]))return c;return-1};lt.LTHelper.$1=function(a,b){var c=a.indexOf(b);lt.LTHelper.version=-1===c?0:parseFloat(a.substr(c+b.length+1))};lt.LTHelper.$2=function(){var a=window.navigator.userAgent.toLocaleLowerCase(),b=window.navigator.appVersion.toLocaleLowerCase(),
c=window.navigator.platform.toLocaleLowerCase(),d="msie";lt.LTHelper.device=0;lt.LTHelper.OS=0;lt.LTHelper.browser=0;if(!lt.LTHelper.OS){var e=lt.LTHelper.$0(a,["iphone","ipod","ipad"]);-1!==e&&(lt.LTHelper.OS=3,lt.LTHelper.browser=4,lt.LTHelper.device=2===e?3:2)}if(!lt.LTHelper.device&&(e=lt.LTHelper.$0(a,["android"]),-1!==e)){lt.LTHelper.OS=4;e=lt.LTHelper.$0(a,["firefox","opera","chrome"]);switch(e){case 0:lt.LTHelper.browser=2;break;case 1:lt.LTHelper.browser=5;break;case 2:lt.LTHelper.browser=
3;break;default:lt.LTHelper.browser=6}e=lt.LTHelper.$0(a,["mobile"]);lt.LTHelper.device=-1!==e?2:3}!lt.LTHelper.device&&-1!==lt.LTHelper.$0(a,["hp-tablet"])&&(lt.LTHelper.device=3,lt.LTHelper.browser=0,lt.LTHelper.OS=7);!lt.LTHelper.device&&-1!==lt.LTHelper.$0(b,["playbook"])&&(lt.LTHelper.device=3,lt.LTHelper.browser=0,lt.LTHelper.OS=6);!lt.LTHelper.device&&-1!==lt.LTHelper.$0(a,["blackberry"])&&(lt.LTHelper.device=2,lt.LTHelper.browser=0,lt.LTHelper.OS=6);!lt.LTHelper.device&&-1!==lt.LTHelper.$0(a,
["iemobile"])&&(lt.LTHelper.device=2,lt.LTHelper.browser=1,lt.LTHelper.OS=1);if(!lt.LTHelper.device){lt.LTHelper.device=1;c=lt.LTHelper.$0(c,["win","mac","linux"]);switch(c){case 0:lt.LTHelper.OS=1;break;case 1:lt.LTHelper.OS=2;break;case 2:lt.LTHelper.OS=5;break;default:lt.LTHelper.OS=0}c=lt.LTHelper.$0(a,"firefox,chrome,safari,opera,msie,trident".split(","));switch(c){case 0:lt.LTHelper.browser=2;break;case 1:lt.LTHelper.browser=3;break;case 2:lt.LTHelper.browser=4;break;case 3:lt.LTHelper.browser=
5;break;case 4:lt.LTHelper.browser=1;break;case 5:lt.LTHelper.browser=1;d="rv";break;default:lt.LTHelper.browser=0}}1===lt.LTHelper.OS&&(c=lt.LTHelper.$0(a,["windows nt 6.2","windows phone os 8","windows phone os 7"]),!c||1===c?lt.LTHelper.OS=9:2===c&&(lt.LTHelper.OS=8));switch(lt.LTHelper.browser){case 1:lt.LTHelper.$1(a,d);break;case 2:lt.LTHelper.$1(a,"firefox");break;case 3:lt.LTHelper.$1(a,"chrome");break;case 4:lt.LTHelper.$1(a,"version");break;case 5:lt.LTHelper.$1(a,"opera");break;case 6:lt.LTHelper.$1(a,
"version");break;default:lt.LTHelper.version=0}lt.LTHelper.vendor=-1!==b.indexOf("webkit")?"Webkit":-1!==a.indexOf("firefox")?"Moz":-1!==a.indexOf("trident")?"ms":-1!==a.indexOf("opera")?"O":""};lt.LTHelper.$3=function(){lt.LTHelper.supportsCanvas="HTMLCanvasElement"in window;lt.LTHelper.supportsTypedArray=void 0!=window.Uint32Array;lt.LTHelper.supportsTouch="ontouchstart"in window;lt.LTHelper.supportsTouch&&7===lt.LTHelper.OS&&(lt.LTHelper.supportsTouch=!1);lt.LTHelper.msPointerEnabled="msPointerEnabled"in
window.navigator&&window.navigator.msPointerEnabled&&"msMaxTouchPoints"in window.navigator&&0<window.navigator.msMaxTouchPoints;lt.LTHelper.msPointerEnabled&&(lt.LTHelper.supportsTouch=!0);if((lt.LTHelper.supportsMultiTouch=lt.LTHelper.supportsTouch)&&4===lt.LTHelper.OS&&2===lt.LTHelper.browser)lt.LTHelper.supportsMultiTouch=!1;lt.LTHelper.supportsMouse=!lt.LTHelper.supportsTouch||1===lt.LTHelper.device;lt.LTHelper.supportsScroll=1===lt.LTHelper.device;lt.LTHelper.supportsWebGL="WebKitCSSMatrix"in
window&&"m11"in new WebKitCSSMatrix;lt.LTHelper.supportsTransform=lt.LTHelper.vendor+"Transform"in document.documentElement.style;lt.LTHelper.supportsTransitionEnd=3===lt.LTHelper.OS||6===lt.LTHelper.OS&&3===lt.LTHelper.device;lt.LTHelper.supportsWebWorker="undefined"!==typeof Worker;lt.LTHelper.resizeEvent="onorientationchange"in window?"orientationchange":"resize";lt.LTHelper.dragStartEvent=lt.LTHelper.supportsTouch?"touchstart":"mousedown";lt.LTHelper.dragDeltaEvent=lt.LTHelper.supportsTouch?"touchmove":
"mousemove";lt.LTHelper.dragCompletedEvent=lt.LTHelper.supportsTouch?"touchend":"mouseup";lt.LTHelper.dragCancelEvent=lt.LTHelper.supportsTouch?"touchcancel":"mouseup";lt.LTHelper.mouseWheelEvent="Moz"===lt.LTHelper.vendor?"DOMMouseScroll":"mousewheel"};lt.LTHelper.$4=function(){for(var a=["ms","moz","webkit","o"],b=!1,c=0;c<a.length&&!b;c++)window.lt_requestAnimationFrame=window[a[c]+"RequestAnimationFrame"],window.lt_cancelAnimationFrame=window[a[c]+"CancelAnimationFrame"]||window[a[c]+"CancelRequestAnimationFrame"],
window.lt_requestAnimationFrame&&(b=!0);lt.LTHelper.supportsAnimationFrame=b;lt.LTHelper.supportsAnimationFrame||(window.lt_requestAnimationFrame=lt.LTHelper.$6,window.lt_cancelAnimationFrame=lt.LTHelper.$7)};lt.LTHelper.$6=function(a){var b=(new Date).getTime(),c=Math.max(0,16-(b-lt.LTHelper.$5)),d=-1,d=setTimeout(function(){a();-1!==d&&clearTimeout(d)},c);lt.LTHelper.$5=b+c;return d};lt.LTHelper.$7=function(a){-1!==a&&clearTimeout(a)};lt.LTHelper.requestAnimationFrame=function(a){return window.lt_requestAnimationFrame(a)};
lt.LTHelper.cancelAnimationFrame=function(a){window.lt_cancelAnimationFrame(a)};lt.LTHelper.getElementStyle=function(a,b){var c=a.style[b];if(!String.isNullOrEmpty(c))return c;a.currentStyle&&(c=a.currentStyle[b]);if(!String.isNullOrEmpty(c))return c;window.getComputedStyle&&(c=document.defaultView.getComputedStyle(a,null).getPropertyValue(b));return c};lt.LTHelper.getPosition=function(a,b){for(var c=0,d=0;null!=a&&a!==b&&!isNaN(a.offsetLeft)&&!isNaN(a.offsetTop);)c+=a.offsetLeft-("body"===a.nodeName.toLowerCase()?
0:a.scrollLeft),d+=a.offsetTop-("body"===a.nodeName.toLowerCase()?0:a.scrollTop),a=a.offsetParent;return lt.LeadPointD.create(c,d)};lt.LTHelper.base64Encode=function(a,b){if(null==a)return null;if(!a.length)return"";for(var c="",d,e,i,k,f,j,h=lt.LTHelper.$9(a,b),l=0;l<h.length;)d=h.charCodeAt(l++),e=h.charCodeAt(l++),i=h.charCodeAt(l++),k=d>>2,d=(d&3)<<4|e>>4,f=(e&15)<<2|i>>6,j=i&63,isNaN(e)?f=j=64:isNaN(i)&&(j=64),c=c+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(k)+
"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(d)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(f)+"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".charAt(j);return c};lt.LTHelper.base64Decode=function(a){if(null==a)return null;if(!a.length)return[];for(var b="",c,d,e,i,k,f=0,a=a.replace(/[^A-Za-z0-9\+\/\=]/g,"");f<a.length;)c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),d="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),
i="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),k="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=".indexOf(a.charAt(f++)),c=c<<2|d>>4,d=(d&15)<<4|i>>2,e=(i&3)<<6|k,b+=String.fromCharCode(c),64!==i&&(b+=String.fromCharCode(d)),64!==k&&(b+=String.fromCharCode(e));return lt.LTHelper.$A(b)};lt.LTHelper.$9=function(a,b){for(var c="",d=0;d<a.length;d++){var e=a[d];if(!b||!(10===e&&0<d&&13===a[d-1]))128>e?c+=String.fromCharCode(e):(127<e&&2048>
e?c+=String.fromCharCode(e>>6|192):(c+=String.fromCharCode(e>>12|224),c+=String.fromCharCode(e>>6&63|128)),c+=String.fromCharCode(e&63|128))}return c};lt.LTHelper.$A=function(a){for(var b=[],c=0,d=0,e=0,i=0;c<a.length;)d=a.charCodeAt(c),128>d?(b.push(d),c++):191<d&&224>d?(e=a.charCodeAt(c+1),d=(d&31)<<6|e&63,b.push(d),c+=2):(e=a.charCodeAt(c+1),i=a.charCodeAt(c+2),d=(d&15)<<12|(e&63)<<6|i&63,b.push(d),c+=3);return b};lt.LTHelper.loadJS=function(a,b){for(var c=!1,d=document.getElementsByTagName("script"),
e=d.length;0<=e&&!c;e--)null!=d[e]&&null!=d[e].getAttribute("src")&&-1!==d[e].getAttribute("src").indexOf(a)&&(c=!0);c||(c=document.createElement("script"),c.setAttribute("type","text/javascript"),c.setAttribute("src",a),c.onload=b,document.getElementsByTagName("head")[0].appendChild(c))};lt.LTHelper.removeJS=function(a){for(var b=document.getElementsByTagName("script"),c=b.length;0<=c;c--)null!=b[c]&&null!=b[c].getAttribute("src")&&-1!==b[c].getAttribute("src").indexOf(a)&&b[c].parentNode.removeChild(b[c])};
lt.LTHelper.$B=function(a){var b=!1;try{var c=a.getContext("2d");if(null==c)return!1;c.beginPath();var d=a.width,e=a.height;c.rect(d-1,e-1,1,1);c.fillStyle="red";c.fill();var i=c.getImageData(d-1,e-1,1,1);null!=i&&255===i.data[0]&&(b=!0);c.clearRect(0,0,d,e)}catch(k){}return b};lt.LTHelper.ensureUsableCanvas=function(a){if(null==a)return 0;var b=a.width,c=a.height;if(!b||!c)return 1;var d=1;if(!lt.LTHelper.$B(a)){for(var d=[4,2],e=-1,i=0,k=0;k<d.length&&-1===e;k++)i=1024*d[k],a.width=i,a.height=i,
lt.LTHelper.$B(a)&&(e=k);-1!==e?(d=i/b,d*c>i&&(d=i/c)):d=0}a.width=parseInt(d*b+0.5);a.height=parseInt(d*c+0.5);return d};lt.InvalidOperationException=function(a){throw Error(a);};lt.ArgumentNullException=function(a){throw Error(String.format("'{0}' cannot be null",a));};lt.ArgumentOutOfRangeException=function(a,b,c){throw Error(String.format("'{0}'\n{1}\nActual value:{2}",a,c,b));};lt.ArgumentException=function(a,b){throw Error(String.format("'{0}'\n{1}",a,b));};lt.Leadtools$1.registerClass("lt.Leadtools$1");
lt.NotifyLeadCollectionChangedEventArgs.registerClass("lt.NotifyLeadCollectionChangedEventArgs",lt.LeadEventArgs);lt.LeadCollection.registerClass("lt.LeadCollection");lt.LeadEventArgs.registerClass("lt.LeadEventArgs");lt.LeadEvent.registerClass("lt.LeadEvent");lt.ImageProcessingProgressEventArgs.registerClass("lt.ImageProcessingProgressEventArgs",lt.LeadEventArgs);lt.ImageProcessingCompletedEventArgs.registerClass("lt.ImageProcessingCompletedEventArgs",lt.LeadEventArgs);lt.ImageProcessingErrorEventArgs.registerClass("lt.ImageProcessingErrorEventArgs",
lt.LeadEventArgs);lt.ImageProcessing.registerClass("lt.ImageProcessing");lt.LeadLengthD.registerClass("lt.LeadLengthD");lt.LeadDoubleTools.registerClass("lt.LeadDoubleTools");lt.LeadMatrix.registerClass("lt.LeadMatrix");lt.Leadtools$2.registerClass("lt.Leadtools$2");lt.LeadPointD.registerClass("lt.LeadPointD");lt.LeadRectD.registerClass("lt.LeadRectD");lt.LeadSizeD.registerClass("lt.LeadSizeD");lt.LTHelper.registerClass("lt.LTHelper");lt.InvalidOperationException.registerClass("lt.InvalidOperationException");
lt.ArgumentNullException.registerClass("lt.ArgumentNullException");lt.ArgumentOutOfRangeException.registerClass("lt.ArgumentOutOfRangeException");lt.ArgumentException.registerClass("lt.ArgumentException");lt.Leadtools$1.$0="LEADTOOLS\ufffd for JavaScript";lt.Leadtools$1.$1="LEAD Technologies, Inc.";lt.Leadtools$1.$2="LEADTOOLS\ufffd is a trademark of LEAD Technologies, Inc.";lt.Leadtools$1.$3="\ufffd 1991-2015 LEAD Technologies, Inc.";lt.Leadtools$1.$4=".dll";lt.Leadtools$1.$5=".exe";lt.Leadtools$1.$6=
"";lt.Leadtools$1.$7="";lt.Leadtools$1.$8="LEADTOOLS\ufffd for JavaScript";lt.Leadtools$1.$9="Leadtools.Xxx.dll";lt.Leadtools$1.$A="LEADTOOLS Xxx";lt.Leadtools$1.$B="lt.dll";lt.Leadtools$1.$C="Leadtools";lt.Leadtools$1.$D="lt.Controls.dll";lt.Leadtools$1.$E="Controls";lt.Leadtools$1.$F="lt.Documents.UI.dll";lt.Leadtools$1.$10="Documents User Interface";lt.Leadtools$1.$11="lt.Controls.Medical.dll";lt.Leadtools$1.$12="Medical Controls";lt.Leadtools$1.$13="lt.Documents.dll";lt.Leadtools$1.$14="Documents";
lt.Leadtools$1.$15="lt.Annotations.Core.dll";lt.Leadtools$1.$16="Annotations Core";lt.Leadtools$1.$17="lt.Annotations.Automation.dll";lt.Leadtools$1.$18="Annotations Automation";lt.Leadtools$1.$19="lt.Annotations.Designers.dll";lt.Leadtools$1.$1A="Annotations Designers";lt.Leadtools$1.$1B="lt.Annotations.Rendering.dll";lt.Leadtools$1.$1C="Annotations Rendering";lt.Leadtools$1.$1D="Leadtools.Ccow.dll";lt.Leadtools$1.$1E="Leadtools CCOW Library";lt.Leadtools$1.$1F="Leadtools.Annotations.Documents.dll";
lt.Leadtools$1.$20="Annotations Documents";lt.Leadtools$1.$21="Leadtools.Annotations.JavaScript.dll";lt.Leadtools$1.$22="JavaScripot Annotations";lt.Leadtools$1.$23="19.0.0.0";lt.Leadtools$1.$24="19.0.0.1";lt.LeadEventArgs.Empty=new lt.LeadEventArgs;lt.LeadDoubleTools.naN=0/0;lt.LeadDoubleTools.positiveInfinity=1/0;lt.LeadDoubleTools.negativeInfinity=-1/0;lt.LeadMatrix.$1=lt.LeadMatrix.$14();lt.LeadPointD.$1=lt.LeadPointD.$2();lt.LeadRectD.$2=lt.LeadRectD.$7();lt.LeadSizeD.$2=lt.LeadSizeD.$5();lt.LTHelper.requestCustomHeaders=
null;lt.LTHelper.device=0;lt.LTHelper.OS=0;lt.LTHelper.browser=0;lt.LTHelper.version=0;lt.LTHelper.vendor=null;lt.LTHelper.supportsCanvas=!1;lt.LTHelper.supportsTypedArray=!1;lt.LTHelper.supportsTouch=!1;lt.LTHelper.supportsMultiTouch=!1;lt.LTHelper.supportsMouse=!1;lt.LTHelper.supportsScroll=!1;lt.LTHelper.supportsWebGL=!1;lt.LTHelper.supportsTransform=!1;lt.LTHelper.supportsTransitionEnd=!1;lt.LTHelper.supportsAnimationFrame=!1;lt.LTHelper.supportsWebWorker=!1;lt.LTHelper.msPointerEnabled=!1;lt.LTHelper.resizeEvent=
null;lt.LTHelper.dragStartEvent=null;lt.LTHelper.dragDeltaEvent=null;lt.LTHelper.dragCompletedEvent=null;lt.LTHelper.dragCancelEvent=null;lt.LTHelper.mouseWheelEvent=null;lt.LTHelper.$5=0;lt.LTHelper.$2();lt.LTHelper.$3();lt.LTHelper.$4();lt.LTHelper.requestCustomHeaders={}})();
